using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using FinkFramework.Runtime.Data;
using FinkFramework.Runtime.Utils;
using UnityEditor;
using UnityEngine;

namespace FinkFramework.Editor.Modules.Data
{
    [Serializable]
    internal sealed class DataGenerationManifest
    {
        public int schemaVersion = 1;
        public string generator = "Fink Framework";
        public string outputRoot = string.Empty;
        public string generatedAtUtc = string.Empty;
        public List<DataGenerationManifestEntry> files = new();
    }

    [Serializable]
    internal sealed class DataGenerationManifestEntry
    {
        public string path = string.Empty;
        public string sha256 = string.Empty;
    }

    /// <summary>
    /// 管理 C# 自动生成文件清单。
    /// 清单固定保存在 ProjectSettings，不随 C# 输出目录移动。
    /// </summary>
    internal static class DataGenerationManifestTool
    {
        public const string GeneratedFileMarker = "// <auto-generated by Fink Framework. Do not edit.>";

        private const string ManifestRelativePath = "ProjectSettings/FinkFramework/DataGenerationManifest.json";
        private const string GeneratorName = "Fink Framework";

        private static string approvedOutputRoot;

        private static string ManifestPath =>
            Path.Combine(DataPipelinePath.ProjectRoot, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));

        public static string ToProjectRelativePath(string absolutePath)
        {
            return PathUtil.NormalizePath(Path.GetRelativePath(DataPipelinePath.ProjectRoot, absolutePath));
        }

        public static bool EnsureOutputPathConfirmed(string currentOutputRoot)
        {
            if (!TryLoad(out DataGenerationManifest previousManifest))
                return true;

            string currentRelativeRoot = ToProjectRelativePath(currentOutputRoot);
            if (string.Equals(previousManifest.outputRoot, currentRelativeRoot, StringComparison.OrdinalIgnoreCase))
                return true;

            if (string.Equals(approvedOutputRoot, currentRelativeRoot, StringComparison.OrdinalIgnoreCase))
                return true;

            if (!ConfirmOutputPathChange(previousManifest, currentOutputRoot))
                return false;

            approvedOutputRoot = currentRelativeRoot;
            return true;
        }

        public static bool TryLoad(out DataGenerationManifest manifest)
        {
            manifest = null;
            if (!File.Exists(ManifestPath))
                return false;

            try
            {
                string json = File.ReadAllText(ManifestPath, Encoding.UTF8).TrimStart('\uFEFF');
                manifest = JsonUtility.FromJson<DataGenerationManifest>(json);
                return manifest != null && !string.IsNullOrEmpty(manifest.outputRoot);
            }
            catch (Exception ex)
            {
                LogUtil.Warn("DataGenerationManifest", $"读取 C# 生成清单失败，将保留旧文件：{ex.Message}");
                return false;
            }
        }

        public static bool TryWrite(string outputRoot, IEnumerable<string> generatedFiles, out string error)
        {
            error = string.Empty;

            try
            {
                var manifest = new DataGenerationManifest
                {
                    generator = GeneratorName,
                    outputRoot = ToProjectRelativePath(outputRoot),
                    generatedAtUtc = DateTime.UtcNow.ToString("O", CultureInfo.InvariantCulture)
                };

                foreach (string file in generatedFiles
                             .Distinct(StringComparer.OrdinalIgnoreCase)
                             .OrderBy(path => ToProjectRelativePath(path), StringComparer.OrdinalIgnoreCase))
                {
                    if (!File.Exists(file))
                        throw new FileNotFoundException($"生成文件不存在：{file}");

                    manifest.files.Add(new DataGenerationManifestEntry
                    {
                        path = PathUtil.NormalizePath(Path.GetRelativePath(outputRoot, file)),
                        sha256 = ComputeSha256(file)
                    });
                }

                string manifestDirectory = Path.GetDirectoryName(ManifestPath);
                if (!string.IsNullOrEmpty(manifestDirectory))
                    Directory.CreateDirectory(manifestDirectory);

                File.WriteAllText(
                    ManifestPath,
                    JsonUtility.ToJson(manifest, true),
                    new UTF8Encoding(false));

                return true;
            }
            catch (Exception ex)
            {
                error = ex.Message;
                return false;
            }
        }

        public static bool ConfirmOutputPathChange(DataGenerationManifest previousManifest, string currentOutputRoot)
        {
            string oldOutputRoot = ResolveProjectPath(previousManifest.outputRoot);
            int fileCount = !string.IsNullOrEmpty(oldOutputRoot) && previousManifest.files != null
                ? previousManifest.files.Count(entry =>
                    TryResolveManifestFile(oldOutputRoot, entry, out string file) && File.Exists(file))
                : 0;
            string oldPath = string.IsNullOrEmpty(oldOutputRoot) ? previousManifest.outputRoot : oldOutputRoot;
            string newPath = ToProjectRelativePath(currentOutputRoot);

            string message =
                $"检测到 C# 生成路径已改变：\n\n" +
                $"旧路径：{previousManifest.outputRoot}\n" +
                $"新路径：{newPath}\n\n" +
                $"清单记录的旧生成文件：{fileCount} 个\n\n" +
                "确认后只会清理清单中登记且未被修改的自动生成文件。\n" +
                "手动修改过的文件会保留。\n\n" +
                $"旧目录：{oldPath}";

            return EditorUtility.DisplayDialog(
                "C# 生成路径已改变",
                message,
                "确认并继续",
                "取消生成");
        }

        public static void CleanupPreviousOutput(
            DataGenerationManifest previousManifest,
            string currentOutputRoot,
            IEnumerable<string> currentGeneratedFiles)
        {
            if (previousManifest == null)
                return;

            string currentRelativeRoot = ToProjectRelativePath(currentOutputRoot);
            bool outputPathChanged = !string.Equals(
                previousManifest.outputRoot,
                currentRelativeRoot,
                StringComparison.OrdinalIgnoreCase);

            int deletedCount = 0;
            int preservedCount = 0;
            string oldOutputRoot = ResolveProjectPath(previousManifest.outputRoot);
            var currentFilePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (!string.IsNullOrEmpty(oldOutputRoot))
            {
                foreach (string path in currentGeneratedFiles)
                {
                    currentFilePaths.Add(PathUtil.NormalizePath(Path.GetRelativePath(oldOutputRoot, path)));
                }
            }

            if (!string.IsNullOrEmpty(oldOutputRoot) && previousManifest.files != null)
            {
                foreach (DataGenerationManifestEntry entry in previousManifest.files)
                {
                    if (!outputPathChanged && currentFilePaths.Contains(entry.path))
                        continue;

                    if (!TryResolveManifestFile(oldOutputRoot, entry, out string file))
                        continue;

                    if (!File.Exists(file))
                        continue;

                    if (!HasGeneratedMarker(file) || !string.Equals(ComputeSha256(file), entry.sha256, StringComparison.OrdinalIgnoreCase))
                    {
                        preservedCount++;
                        continue;
                    }

                    File.Delete(file);
                    deletedCount++;
                }

                DeleteEmptySubdirectories(oldOutputRoot);
            }

            if (preservedCount > 0)
            {
                LogUtil.Warn(
                    "DataGenerationManifest",
                    $"旧生成目录保留了 {preservedCount} 个被修改或缺少标记的文件，已清理 {deletedCount} 个安全文件：{previousManifest.outputRoot}");
            }
            else if (deletedCount > 0)
            {
                LogUtil.Info("DataGenerationManifest", $"已清理旧生成目录中的 {deletedCount} 个自动生成文件：{previousManifest.outputRoot}");
            }

            approvedOutputRoot = null;
        }

        public static string AddGeneratedFileMarker(string code)
        {
            if (code.StartsWith(GeneratedFileMarker, StringComparison.Ordinal))
                return code;

            return GeneratedFileMarker + "\n" + code;
        }

        private static string ResolveProjectPath(string projectRelativePath)
        {
            if (string.IsNullOrWhiteSpace(projectRelativePath))
                return string.Empty;

            string projectRoot = Path.GetFullPath(DataPipelinePath.ProjectRoot);
            string candidate = Path.GetFullPath(Path.Combine(
                projectRoot,
                projectRelativePath.Replace('/', Path.DirectorySeparatorChar)));

            return IsPathInside(projectRoot, candidate) ? candidate : string.Empty;
        }

        private static bool TryResolveManifestFile(
            string outputRoot,
            DataGenerationManifestEntry entry,
            out string file)
        {
            file = string.Empty;
            if (entry == null || string.IsNullOrWhiteSpace(entry.path))
                return false;

            string candidate = Path.GetFullPath(Path.Combine(
                outputRoot,
                entry.path.Replace('/', Path.DirectorySeparatorChar)));

            if (!IsPathInside(outputRoot, candidate))
                return false;

            file = candidate;
            return true;
        }

        private static bool IsPathInside(string root, string path)
        {
            string normalizedRoot = Path.GetFullPath(root)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) +
                Path.DirectorySeparatorChar;
            string normalizedPath = Path.GetFullPath(path);
            return normalizedPath.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase);
        }

        private static bool HasGeneratedMarker(string file)
        {
            using var reader = new StreamReader(file, Encoding.UTF8, true);
            for (int i = 0; i < 8 && !reader.EndOfStream; i++)
            {
                if ((reader.ReadLine()?.IndexOf(GeneratedFileMarker, StringComparison.Ordinal) ?? -1) >= 0)
                    return true;
            }

            return false;
        }

        private static string ComputeSha256(string file)
        {
            using var sha256 = SHA256.Create();
            using var stream = File.OpenRead(file);
            return BitConverter.ToString(sha256.ComputeHash(stream))
                .Replace("-", string.Empty)
                .ToLowerInvariant();
        }

        private static void DeleteEmptySubdirectories(string root)
        {
            if (!Directory.Exists(root))
                return;

            foreach (string directory in Directory.GetDirectories(root, "*", SearchOption.AllDirectories)
                         .OrderByDescending(path => path.Length))
            {
                if (Directory.Exists(directory) &&
                    !Directory.EnumerateFileSystemEntries(directory).Any())
                    Directory.Delete(directory);
            }
        }
    }
}
